default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>


development:
  <<: *default
  database: <%= ENV['DATABASE_URL'] %>

test:
  <<: *default
  database: irpsf_test

production:
  <<: *default
  database: <%= ENV['DATABASE_NAME'] %>
  url: <%= ENV['DATABASE_URL'] %>
  prepared_statements: false

